---
- name: add and enable fast-vm yum repository
  when: config_repositories|bool
  yum_repository:
    name: 'ondrejhome-fast-vm'
    description: 'Copr repo for fast-vm owned by ondrejhome'
    baseurl: "{{ baseurl }}"
    skip_if_unavailable: yes
    gpgkey: 'https://copr-be.cloud.fedoraproject.org/results/ondrejhome/fast-vm/pubkey.gpg'
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: no

- name: enable 'optional' and 'extras' RPMs repository on RHEL systems
  command: subscription-manager repos --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-extras-rpms
  when: config_repositories|bool and ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
  ignore_errors: True
  ## we ignore if this fails because we might have access to needed packages via other repository
