---
## we need libvirt to be started to do any changes to libvirt networks
- name: ensure that libvirtd service is started
  service: name=libvirtd state=started

## virt_net commands must be separate as the virt_net cannot handle 'state'/'command'/'autostart' together
- name: define fast-vm-nat libvirt network
  virt_net:
    command: define
    name: '{{ fastvm_net_name }}'
    xml: '{{ lookup("template", "fast-vm-nat.xml.j2") }}'

- name: start fast-vm-nat libvirt network
  virt_net:
    state: active
    name: '{{ fastvm_net_name }}'

- name: enable fast-vm-nat libvirt network on boot
  virt_net:
    autostart: yes
    name: '{{ fastvm_net_name }}'
