---
- name: configure unified fast-vm yum repository (Fedora)
  when:
    - config_repositories|bool
    - ansible_facts["distribution"] == 'Fedora'
  copy:
     dest: '/etc/yum.repos.d/fast-vm.repo'
     content: |
         [fast-vm]
         name=fast-vm
         baseurl=https://www.famera.cz/fast-vm-repo/unified-rpm-fedora/
         enabled=1
         metadata_expire=7d
         repo_gpgcheck=1
         type=rpm
         gpgcheck=1
         gpgkey=https://www.famera.cz/fast-vm-repo/fast-vm-repo-2026-2031-eddsa.gpg.txt

- name: configure unified fast-vm yum repository (EL)
  when:
    - config_repositories|bool
    - ansible_facts["distribution"] in ['RedHat', 'CentOS', 'AlmaLinux']
  copy:
     dest: '/etc/yum.repos.d/fast-vm.repo'
     content: |
         [fast-vm]
         name=fast-vm
         baseurl=https://www.famera.cz/fast-vm-repo/unified-rpm-el/
         enabled=1
         metadata_expire=7d
         repo_gpgcheck=1
         type=rpm
         gpgcheck=1
         gpgkey=https://www.famera.cz/fast-vm-repo/fast-vm-repo-2026-2031-rsa.gpg.txt

- name: configure fast-vm-epel-deps yum repository (EL)
  when:
    - config_repositories|bool
    - ansible_facts["distribution"] in ['RedHat', 'CentOS', 'AlmaLinux']
  copy:
    dest: '/etc/yum.repos.d/epel-deps.repo'
    content: |
        [fast-vm-epel-deps]
        name=fast-vm dependencies from Extra Packages for Enterprise Linux $releasever - $basearch
        metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
        enabled=1
        gpgcheck=1
        gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
        includepkgs=
         pv

- name: Debian/Ubuntu repository configuration
  when:
    - config_repositories|bool
    - ansible_facts["distribution"] in ['Debian', 'Ubuntu']
  block:
    - name: configure unified fast-vm apt repository (Debian/Ubuntu)
      copy:
        dest: '/etc/apt/sources.list.d/fast-vm.list'
        content: |
            deb [signed-by=/etc/apt/keyrings/fast-vm-repo-2026-2031.gpg] https://www.famera.cz/fast-vm-repo unified-deb/

    - name: get gpg key for apt repo (dearmored)
      get_url:
        url: https://www.famera.cz/fast-vm-repo/fast-vm-repo-2026-2031-eddsa.gpg
        dest: /etc/apt/keyrings/fast-vm-repo-2026-2031.gpg

    - name: refresh apt cache
      ansible.builtin.apt:
        update_cache: true
