---
- name: yum install packages
  when: ansible_distribution != 'Fedora'
  yum: name="{{ item }}" state=present
  with_items: "{{ yum_packages_fastvm }}"

- name: dnf install packages
  when: ansible_distribution == 'Fedora'
  dnf: name="{{ item }}" state=present
  with_items: "{{ dnf_packages_fastvm }}"

- name: enable libvirtd service on boot
  service: name=libvirtd enabled=yes
