---
- name: yum install packages
  yum:
    name: "{{ yum_packages_fastvm }}"
    state: 'present'
  when: ansible_distribution != 'Fedora'

- name: dnf install packages
  dnf:
    name: "{{ dnf_packages_fastvm }}"
    state: 'present'
  when: ansible_distribution == 'Fedora'

- name: enable libvirtd service on boot
  service:
    name: 'libvirtd'
    enabled: yes
