---
- name: yum install packages
  when: ansible_distribution != 'Fedora'
  yum: name="{{ item }}" state=present
  with_items:
    - fast-vm
    - dnsmasq-utils
    - libguestfs-tools-c
    - bash-completion
    - python-lxml
    - libvirt-python

- name: dnf install packages
  when: ansible_distribution == 'Fedora'
  dnf: name="{{ item }}" state=present
  with_items:
    - fast-vm
    - dnsmasq-utils
    - libguestfs-tools-c
    - bash-completion
    - python-lxml
    - libvirt-python
    - libselinux-python

- name: enable libvirtd service on boot
  service: name=libvirtd enabled=yes
