---
- name: install custom qemu-kvm, qemu-img and seabios-bin packages
  yum:
    name:
      - qemu-img
      - qemu-kvm
      - qemu-kvm-common
      - seabios-bin
    enablerepo: 'ondrejhome-fast-vm'
    disablerepo: '*'
    state: 'latest'
    update_only: true
