---
- name: install packages
  package:
    name: "{{ packages_fastvm }}"
    state: 'present'

- name: install fast-vm DEB package directly
  apt:
    deb: "{{ packages_fastvm_deb }}"
    state: 'present'
  when: ansible_distribution in ['Debian', 'Ubuntu' ]

- name: install firewalld
  package:
    name: 'firewalld'
    state: 'present'
  when: use_firewalld|bool

- name: enable libvirtd service on boot
  service:
    name: 'libvirtd'
    enabled: yes

- name: Enable and start firewalld service
  service:
    name: 'firewalld'
    enabled: true
    state: 'started'
  when: use_firewalld|bool
