---
- name: install ovmf-symlink on EL systems
  ansible.builtin.dnf:
    name: ovmf-symlink
  when: ansible_facts["distribution"] in [ 'AlmaLinux', 'RedHat' ]

- name: install DEB ovmf-symlink
  ansible.builtin.apt:
    cache_valid_time: 3600
    name: ovmf-symlink
  when: ansible_facts["distribution"]+ansible_facts["distribution_major_version"] in [ 'Debian13', 'Ubuntu24' ]

- name: get details about present OVMF files
  ansible.builtin.stat:
    path: "{{ item }}"
    get_attributes: false
    get_checksum: false
  register: ovmf_files
  changed_when: false
  check_mode: false
  loop:
    - '/usr/share/OVMF/OVMF_CODE.fd'
    - '/usr/share/OVMF/OVMF_VARS.fd'

- name: check if OVMF file exists
  ansible.builtin.fail:
    msg: "File {{ item }} doesn't exists"
  when: not ( ovmf_files['results'] | selectattr('item','eq',item) | first )['stat']['exists'] | bool
  loop:
    - '/usr/share/OVMF/OVMF_CODE.fd'
    - '/usr/share/OVMF/OVMF_VARS.fd'
