---
- name: install fence_virtd packages
  package:
    name: "{{ packages_fence_virtd }}"
    state: 'present'

- name: create /etc/cluster directory
  file:
    path: '/etc/cluster'
    state: 'directory'
    mode: '0755'

- name: generate fence_xvm key
  command: dd if=/dev/urandom of=/etc/cluster/fence_xvm.key bs=4k count=1
  notify: restart fence_virtd service
  args:
    creates: /etc/cluster/fence_xvm.key

# https://github.com/ClusterLabs/fence-agents/pull/513
- name: copy fence_xvm.key into fence_xvm-protected.key file with stricter permissions
  copy:
    remote_src: true
    src: /etc/cluster/fence_xvm.key
    dest: /etc/cluster/fence_xvm-protected.key
    mode: '0600'

- name: make fence_xvm.key readable by everyone
  file:
    path: '/etc/cluster/fence_xvm.key'
    mode: '0644'
  notify: restart fence_virtd service

- name: generate /etc/fence_virt.conf configuration
  template:
    src: 'fence_virt.conf.j2'
    dest: '/etc/fence_virt.conf'
    mode: '0600'
  notify: restart fence_virtd service

- name: configure firewall for fence_virtd
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: 'enabled'
    immediate: true
  with_items:
    - '1229/tcp'
    - '1229/udp'
  when: use_firewalld|bool

- name: start and enable fence_virtd service
  service:
    name: 'fence_virtd'
    state: 'started'
    enabled: yes
