---

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: config_repositories
  include: config_repositories.yml
  when: config_repositories == true

- name: install_fastvm
  include: install_fastvm.yml
  when: install_fastvm == true

- name: config_libvirt_access
  include: config_libvirt_access.yml
  when: config_libvirt_access == true

- name: config_libvirt_network
  include: config_libvirt_network.yml
  when: config_libvirt_network == true

- name: create a thinpool LV for fast-vm storage
  lvol: vg={{ fastvm_vg }} size={{ fastvm_lv_size }} lv={{ fastvm_lv }} opts='-T' state=present
  when: config_storage == true

- name: configure group in for fast-vm access in sudoers
  lineinfile: dest=/etc/sudoers.d/fast-vm-sudoers regexp='.*/usr/libexec/fast-vm-helper.sh$' line="%{{ fastvm_group }} ALL=(root) NOPASSWD{{ ':' }} /usr/libexec/fast-vm-helper.sh"
  when: config_sudoers == true

- name: configure fast-vm.conf
  template: src=fast-vm.conf.j2 dest=/etc/fast-vm.conf
  when: config_fastvm_conf == true

- name: install_ovmf (CentOS/RHEL)
  include: install_ovmf.yml
  when: install_ovmf == true and ansible_distribution != 'Fedora'

- name: install_ovmf (Fedora)
  include: install_ovmf_fedora.yml
  when: install_ovmf == true and ansible_distribution == 'Fedora'

- name: install_fence_virtd
  include: install_fence_virtd.yml
  when: install_fence_virtd == true

- name: install_custom_qemu
  include: install_custom_qemu.yml
  when: install_custom_qemu == true and ansible_distribution != 'Fedora'
