---

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: config_repositories
  include_tasks: config_repositories.yml
  when: config_repositories|bool

- name: install_fastvm
  include_tasks: install_fastvm.yml
  when: install_fastvm|bool

- name: config_libvirt_access
  include_tasks: config_libvirt_access.yml
  when: config_libvirt_access|bool

# flush handlers to reload libvirt if needed
- meta: flush_handlers

- name: config_libvirt_network
  include_tasks: config_libvirt_network.yml
  when: config_libvirt_network|bool

- name: create a thinpool LV for fast-vm storage
  lvol:
    vg: "{{ fastvm_vg }}"
    size: "{{ fastvm_lv_size }}"
    lv: "{{ fastvm_lv }}"
    opts: '-T'
    state: 'present'
  when: config_storage|bool

- name: configure group in for fast-vm access in sudoers
  lineinfile:
    dest: '/etc/sudoers.d/fast-vm-sudoers'
    regexp: '.*/usr/libexec/fast-vm-helper.sh$'
    line: "%{{ fastvm_group }} ALL=(root) NOPASSWD{{ ':' }} /usr/libexec/fast-vm-helper.sh"
  when: config_sudoers|bool

- name: configure fast-vm.conf
  template:
    src: 'fast-vm.conf.j2'
    dest: '/etc/fast-vm.conf'
  when: config_fastvm_conf|bool

- name: install_ovmf (CentOS/RHEL)
  include_tasks: install_ovmf.yml
  when: install_ovmf|bool and ansible_distribution != 'Fedora'

- name: install_ovmf (Fedora)
  include_tasks: install_ovmf_fedora.yml
  when: install_ovmf|bool and ansible_distribution == 'Fedora'

- name: install_fence_virtd
  include_tasks: install_fence_virtd.yml
  when: install_fence_virtd|bool

- name: install_custom_qemu
  include_tasks: install_custom_qemu.yml
  when: install_custom_qemu|bool and ansible_distribution != 'Fedora'
