---
- name: restart libvirtd service
  ansible.builtin.service:
    name: 'libvirtd'
    state: 'restarted'

- name: restart fence_virtd service
  ansible.builtin.service:
    name: 'fence_virtd'
    state: 'restarted'
